/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AccessRequest } from "./AccessRequest";
export type { DoctorManagement } from "./DoctorManagement";
export type { EmergencyAccess } from "./EmergencyAccess";
export type { HealthAnalytics } from "./HealthAnalytics";
export type { HealthChainRoles } from "./HealthChainRoles";
export type { HealthRecord } from "./HealthRecord";
export type { IoTData } from "./IoTData";
