/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AccessRequest__factory } from "./AccessRequest__factory";
export { DoctorManagement__factory } from "./DoctorManagement__factory";
export { EmergencyAccess__factory } from "./EmergencyAccess__factory";
export { HealthAnalytics__factory } from "./HealthAnalytics__factory";
export { HealthChainRoles__factory } from "./HealthChainRoles__factory";
export { HealthRecord__factory } from "./HealthRecord__factory";
export { IoTData__factory } from "./IoTData__factory";
